; Sprite2asm trees-leaves-mcd9.png 7 mei 2020 11:25:56
; 0 (0,0)
!byte $00,$44,$50,$04,$8c,$b8,$0c,$ce,$c0,$22,$10,$a0,$0c,$c7,$c8,$88,$8c,$a9,$ec,$b2,$ce
!byte $22,$de,$e0,$be,$02,$b8,$c3,$a7,$aa,$28,$10,$ee,$69,$bb,$b9,$aa,$ba,$ba,$38,$22,$f9
!byte $2e,$ea,$38,$1e,$6b,$a2,$03,$8c,$a2,$2e,$ee,$ac,$2a,$ba,$eb,$ab,$aa,$28,$3a,$cb,$ae
!byte $00
; 1 (0,21)
!byte $08,$e6,$e0,$a2,$2c,$e4,$28,$ae,$89,$09,$ea,$2a,$aa,$aa,$a8,$2e,$ae,$ae,$aa,$aa,$ea
!byte $6b,$ab,$e0,$b6,$aa,$ac,$ba,$e8,$f8,$ae,$ae,$fa,$ef,$ad,$ee,$fb,$da,$bb,$3a,$fb,$ba
!byte $3e,$bb,$2b,$0b,$be,$ec,$0e,$ee,$ec,$0e,$eb,$f0,$0e,$ee,$f0,$02,$ef,$c0,$1f,$df,$54;,$02,$ef,$c0
!byte $00
; Sprite2asm treestest-mc09.png 7 mei 2020 11:25:56
; 0 (0,0)
!byte $1f,$dd,$d4,$1f,$df,$54,$1f,$dd,$d4,$1f,$df,$54,$1d,$dd,$d4,$1d,$df,$54,$1d,$dd,$d4
!byte $1d,$df,$54,$1d,$dd,$55,$1d,$d5,$f5,$1d,$d5,$f5,$1d,$d5,$f5,$1d,$dd,$f5,$1d,$dd,$d5
!byte $1d,$dd,$54,$1d,$df,$54,$1f,$dd,$d4,$1f,$df,$54,$1f,$dd,$d4,$1f,$df,$54,$1f,$dd,$d4
!byte $00
; 1 (0,21)
!byte $1f,$df,$54,$1f,$dd,$d4,$1f,$df,$54,$1f,$dd,$d4,$5f,$df,$54,$7f,$dd,$d4,$7f,$df,$54
!byte $7f,$dd,$d4,$5f,$df,$54,$1f,$dd,$d4,$1f,$df,$54,$1f,$dd,$d5,$1f,$df,$55,$1f,$dd,$d5
!byte $1f,$df,$55,$1d,$dd,$d5,$1d,$df,$55,$1d,$dd,$d5,$1d,$df,$55,$1d,$dd,$d5,$1d,$df,$55
!byte $00
; 2 (0,42)
!byte $1d,$fd,$d5,$1d,$ff,$55,$1d,$fd,$d5,$1d,$ff,$55,$1d,$fd,$d5,$1d,$ff,$55,$1d,$fd,$d5
!byte $1f,$ff,$55,$1f,$fd,$55,$0f,$fd,$54,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
!byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
!byte $00
